### ISSUE TITLE
Version 0.3.2 missing precompiled NIFs

### ISSUE THREAD

**Issue by thiagopromano** [mrdotb/resvg_nif#66]
Hey,

It seems that the latest version of resvg published on hex didn't include the checksums for all targets, only for `x86_64-unknown-linux-gnu`.

https://preview.hex.pm/preview/resvg/0.3.2/show/checksum-Elixir.Resvg.Native.exs

Best Regards,
Thiago Romano

**Comment by thiagopromano** [comment]
![image](https://github.com/mrdotb/resvg_nif/assets/2577646/36ebae85-b8a3-4403-82c5-54e3a83e205e)

**Comment by mrdotb** [comment]
Hello,

Thanks for the info I made a mistake on the last update 🙃
It seems hex is caching the file for 0.3.2 I published the correct one but it does not appear.
I'm deploying 0.3.3 with the correct checksum.

**Comment by mrdotb** [comment]
I can't get the OSX builder to finish the action yet.
I hex retired 0.3.2
I will deploy 0.3.3 with the correct checksum as soon the OSX builder pick up and complete the work.
